s='cosmicspirit'
#print(s.capitalize())
#print(s.isupper())
#print(s.islower())
#print(s.lower())
#print(s.upper())
#print(s.strip(),"hi")
# #print(s.split())
# print(s.startswith('c'))
#print(s.endswith('t'))
#print(s.count('i'))
#print(s.index('v'))
#print(s.find('g'))
#print(s.center(30))
